---
- name: include_tasks ░ OpenLDAP client
  include_tasks: "{{ (ansible_facts.distribution|replace(' ','_')) }}/client.yml"
  when: openldap_client is defined and openldap_client
  tags:
    - internal

- name: include_tasks ░ OpenLDAP server
  include_tasks: "{{ (ansible_facts.distribution|replace(' ','_')) }}/server.yml"
  when: openldap_server is defined and openldap_server
  tags:
    - internal